# Python Portal Executor Test Suite
# Comprehensive testing for secure execution service

version: '3.8'

services:
  executor-test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      PORT: 3002
      EXECUTION_TIMEOUT: 5000
      MEMORY_LIMIT: 64
      MAX_OUTPUT_LENGTH: 5000
      MAX_CODE_LENGTH: 10000
      ENABLE_SANDBOX: true
      PYTHON_PATH: python3
    ports:
      - "3002:3002"
    volumes:
      - /tmp/python-portal-test:/tmp/python-portal
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    networks:
      - executor-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/health/live', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  executor-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: executor-br0
    ipam:
      config:
        - subnet: 172.20.0.0/16